# General Settings
name: Anthony Rabine
job_title: Firmware, Qt, Android freelancer
email: anthony@rabine.fr
description: Je suis un spécialiste du développement embarqué et architecte firmware. J'adore créer des outils et des jeux, surtout avec Qt sur PC et mobile (Android). Je peux travailler pour vous !
avatar: /cv/img/me.jpg
favicon: /favicon.png
# twitter_handler: your_handler
# analytics_code: UA-XXXXXXX-2
# disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/AnthonyRabine' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/anthony-rabine/' }
-  { name: skype, url: 'arabine' }
-  { name: github, url: 'http://github.com/arabine' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 0
show_menu: 1
fixed_sidebar: 1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title/
category_dir: categories

# Pagination
paginate: 3
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->
highlighter: rouge # or pygments or null

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
